[package]
name = "snarky-deriver"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "The inner library of kimchi, for derive macros"
repository = "https://github.com/o1-labs/proof-systems"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
itertools = "0.10.5"
proc-macro2 = "1.0.43"
quote = "1.0.21"
syn = { version = "1.0.109", features = ["full"] }
