[workspace]
members = [
    "book",
    "turshi",
    "curves",
    "groupmap",
    "hasher",
    "kimchi",
    "kimchi/snarky-deriver/",
    "circuit-construction",
    "poseidon",
    "poseidon/export_test_vectors",
    "poly-commitment",
    "signer",
    "tools/kimchi-visu",
    "utils",
]

[profile.release]
lto = true
panic = 'abort'
# codegen-units = 1
