[workspace]
members = [
    "cairo",
    "curves",
    "groupmap",
    "hasher",
    "kimchi",
    "circuit-construction",
    "ocaml/ocaml-gen",
    "ocaml/ocaml-gen/derive",
    "oracle",
    "oracle/export_test_vectors",
    "pickles",
    "poly-commitment",
    "signer",
    "tools/kimchi-visu",
    "utils",
]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
