[package]
name = "mina-curves"
version = "0.1.0"
description = "The set of curves Mina protocol uses"
repository = "https://github.com/o1-labs/proof-systems"
homepage = "https://o1-labs.github.io/proof-systems/"
documentation = "https://o1-labs.github.io/proof-systems/rustdoc/"
readme = "../README.md"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ark-pallas = { version = "0.4.0", default-features = false, features = [ "scalar_field", "base_field" ] }
ark-ec = { version = "0.4.0", features = ["parallel"] }
ark-ff = { version = "0.4.0", features = ["parallel", "asm"] }
ark-std = { version = "0.4.0", features = ["parallel"] }

[dev-dependencies]
ark-relations = { version = "0.4.0", default-features = false }
ark-serialize = { version = "0.4.0", default-features = false }
ark-algebra-test-templates = { version = "0.4.0", default-features = false }
