[package]
name = "mina-curves"
version = "0.1.0"
description = "The set of curves Mina protocol uses"
repository = "https://github.com/o1-labs/proof-systems"
homepage = "https://o1-labs.github.io/proof-systems/"
documentation = "https://o1-labs.github.io/proof-systems/rustdoc/"
readme = "../README.md"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ark-ec = { version = "0.3.0", features = ["parallel"] }
ark-ff = { version = "0.3.0", features = ["parallel", "asm"] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
ark-serialize = "0.3.0"
ark-std = "0.3.0"
num-bigint = { version = "0.4.0" }
o1-utils = { path = "../utils" }
paste = "1.0.9"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"
zeroize = "1.5.5"

# for ocaml
ocaml = { version = "0.22.2", optional = true }
ocaml-gen = { version = "0.1.0", optional = true }

[dev-dependencies]
ark-algebra-test-templates = "0.3.0"
ark-std = "0.3.0"

[features]
default = []
ocaml_types = [ "ocaml", "ocaml-gen" ]
