[package]
name = "mina-curves"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ark-ec = { version = "0.3.0", features = ["parallel"] }
ark-ff = { version = "0.3.0", features = ["parallel", "asm"] }
ark-serialize = "0.3.0"
ark-std = "0.3.0"
num-bigint = { version = "0.4.0" }
zeroize = "1.5.5"

# for ocaml
ocaml = { version = "0.22.2", optional = true }
ocaml-gen = { version = "0.1.0", optional = true }

[dev-dependencies]
rand = { version = "0.8.0", default-features = false }
ark-algebra-test-templates = "0.3.0"
ark-std = "0.3.0"


[features]
default = []
ocaml_types = [ "ocaml", "ocaml-gen" ]
