[metadata]
name = "Polynomial Commitment"
description = "This specification describes the Kimchi polynomial commitment."
version = "0.1.0"
authors = ["TODO"]

[config]
template = "specification.md"

[sections]
srs = "../../poly-commitment/src/srs.rs"
commit = "../../poly-commitment/src/commitment.rs"
