[metadata]
name = "Polynomial Commitment"
description = "This specification describes the Kimchi polynomial commitment."
version = "0.1.0"
authors = ["David Wong"]

[sections]
overview = ["overview.md"]
verifier = ["../../dlog/commitment/src/lib.rs"]
