[package]
name = "plonk-wasm"
version = "0.1.0"
authors = ["opensource@o1labs.org"]
description = "WASM stubs for plonk proof systems"
repository = "https://github.com/MinaProtocol/mina"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "plonk_wasm"
crate-type = ["cdylib"]

################################# Dependencies ################################

[dependencies]
array-init = "2.0.0"
base64.workspace = true
console_error_panic_hook = { version = "0.1.6" }
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3"
libc = "0.2.62"
num-bigint.workspace = true
once_cell = "1.10.0"
paste = "1.0.5"
proc-macro2.workspace = true
quote.workspace = true
rand.workspace = true
rayon.workspace = true
rmp-serde.workspace = true
sprs = { version = "0.11.0" }
spmc = { version = "0.3.0" }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde-wasm-bindgen = ">=0.4"
# Check it is up-to-date with the version in proof-systems/Cargo.toml
wasm-bindgen.workspace = true

web-sys = { version = "0.3.35", features = [
  "Window",
  "Document",
  "HtmlElement",
  "Text",
  "Node",
  "Element",
] }

# arkworks
ark-ec.workspace = true
ark-ff.workspace = true
ark-poly.workspace = true
ark-serialize = "0.4.2"

# proof-systems
groupmap.workspace = true
kimchi = {workspace = true, features = [ "wasm_types" ] }
mina-curves.workspace = true
mina-poseidon.workspace = true
o1-utils.workspace = true
poly-commitment.workspace = true

[dev-dependencies]
wasm-bindgen-test = ">=0.3.0"

[features]
nodejs = []

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
#wasm-opt = ["-O4", "--detect-features", "--enable-mutable-globals" ]
#wasm-opt = ["-O4", "--enable-mutable-globals"]

[build]
rustflags = [
  "-C",
  "target-feature=+atomics,+bulk-memory",
  "-C",
  "link-arg=--no-check-features",
]

[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "target-feature=+atomics,+bulk-memory",
  "-C",
  "link-arg=--no-check-features",
]
