name: Deploy Specifications & Docs to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup OCaml (because of ocaml-gen)
        run: sudo apt update && sudo apt install ocaml

      - name: Build Rust Documentation
        run: |
          rustup install nightly
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --all --no-deps

      - name: Check that up-to-date specification is checked in
        run: |
          cargo install cargo-spec
          cd specifications/kimchi
          cargo spec ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Hugo
        run: |
          cd specifications/website
          hugo --minify --buildDrafts=false

      - name: Arrange website folder hierarchy
        run: |
          mv ./specifications/website/public ./website
          mv ./target/doc ./website/rustdoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
